services:
  lightline-node:
    build: .
    restart: always
    network_mode: host
    env_file: .env

    environment:
      SSL_CERT_FILE: "/var/lib/lightline-node/ssl_cert.pem"
      SSL_KEY_FILE: "/var/lib/lightline-node/ssl_key.pem"
      SSL_CLIENT_CERT_FILE: "/var/lib/lightline-node/ssl_client_cert.pem"

    volumes:
      - /var/lib/lightline-node:/var/lib/lightline-node
      - /etc/shadowsocks:/etc/shadowsocks
